spring.application.name=hidechat-backend
spring.data.redis.host=equal-hamster-94596.upstash.io
spring.data.redis.port=6379
spring.data.redis.password=gQAAAAAAAXGEAAIncDJkYzRjYzNiZTM5NmY0MTY0YTdiMmUwMDliYTY1ODdlN3AyOTQ1OTY
spring.data.redis.ssl.enabled=true